services:
  backend:
    build: ./backend
    container_name: medi-backend
    ports:
      - "${EXTERNAL_PORT}:${PORT}"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    restart: always
    networks:
      - medi-net
    volumes:
      - ./backend/logs:/app/logs

  db:
    image: mysql:8.0.34
    container_name: medi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: meditalk
      MYSQL_USER: mediuser
      MYSQL_PASSWORD: medi1234
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_PORT}"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - medi-net

networks:
  medi-net:

volumes:
  mysql-data:

