services:
  db:
    image: mysql:8.0.34
    container_name: medi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: meditalk
      MYSQL_USER: mediuser
      MYSQL_PASSWORD: medi1234
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_PORT}"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - medi-net

  opencv:
    build: ./opencv
    container_name: medi-opencv
    ports:
      - "${OPENCV_EXTERNAL_PORT}:${OPENCV_PORT}"
    restart: always
    networks:
      - medi-net
    depends_on:
      - db
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  backend:
    build: ./backend
    container_name: medi-backend
    ports:
      - "${EXTERNAL_PORT}:${PORT}"   # 외부 공개는 백엔드만
    env_file:
      - ./.env
    depends_on:
      - db
      - opencv
    restart: always
    networks:
      - medi-net
    volumes:
      - ./backend/logs:/app/logs

  backend_app:
    build: ./Backend_app
    container_name: medi-backend-app
    ports:
      - "${APP_EXTERNAL_PORT}:${APP_PORT}"
    env_file:
      - ./.env
    depends_on:
      - db
      - opencv
      - backend
    restart: always
    networks:
      - medi-net
    volumes:
      - ./Backend_app/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]   # 응답만 있으면 OK
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  medi-net:
 

volumes:
  mysql-data:

